### ISSUE TITLE
The problem discovered today

### ISSUE THREAD

**Issue by DuJiming** [openstf/adbkit-apkreader#19]
Make a mistake
```javascrpit
const reader = await ApkReader.open('coins.apk');
const manifest = await reader.readManifest();
```
```
  Error: end of central directory record signature not found
      at /Users/workspace/demo/node_modules/yauzl/index.js:187:14
      at Immediate._onImmediate (/Users/workspace/demo/node_modules/yauzl/index.js:624:38)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
```

**Comment by DuJiming** [comment]
sorry，is path
